//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class VoxScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, CONT_IF=15, CONT_ELSE=16, 
		CONT_FOR=17, CONT_FOR_AT=18, CONT_FOR_ADD=19, CONT_FOR_REP=20, CONT_FOR_FROM=21, 
		CONT_FOR_TO=22, CONT_FOR_PER=23, CONT_WHILE=24, CONT_RETURN=25, CONT_BREAK=26, 
		CONT_CONTINUE=27, OBJ_FUNCTION=28, OBJ_TYPE=29, OBJ_VAR=30, OBJ_CONST=31, 
		NUMBER=32, STRING=33, BOOLEAN=34, ID=35, MUL_DIV=36, ADD_SUB=37, COMPARE=38, 
		PLUS=39, MINUS=40, MULTIPLY=41, DIVIDE=42, EXPONENT=43, EQUALS=44, INCREMENT=45, 
		DECREMENT=46, ADD_DIRECT=47, SUB_DIRECT=48, MULT_DIRECT=49, DIV_DIRECT=50, 
		EXPO_DIRECT=51, COND_EQUAL=52, COND_NOTEQUAL=53, COND_GREATERTHAN=54, 
		COND_LESSTHAN=55, COND_GREATEROREQUAL=56, COND_LESSOREQUAL=57, COND_AND=58, 
		COND_OR=59, WS=60, LINE_COMMENT=61, MULTILINE_COMMENT=62;
	public const int
		RULE_program = 0, RULE_actionSet = 1, RULE_action = 2, RULE_cont_if = 3, 
		RULE_cont_else = 4, RULE_cont_while = 5, RULE_cont_for = 6, RULE_cont_return = 7, 
		RULE_cont_break = 8, RULE_cont_continue = 9, RULE_func_call = 10, RULE_func_define = 11, 
		RULE_var_define = 12, RULE_var_set = 13, RULE_var_inst = 14, RULE_for_object = 15, 
		RULE_for_repeat = 16, RULE_for_range = 17, RULE_expression = 18, RULE_object = 19, 
		RULE_objItem = 20, RULE_array = 21, RULE_identifier = 22, RULE_iden_seg = 23, 
		RULE_iden_seg_text = 24, RULE_iden_seg_expr = 25, RULE_func_expr = 26;
	public static readonly string[] ruleNames = {
		"program", "actionSet", "action", "cont_if", "cont_else", "cont_while", 
		"cont_for", "cont_return", "cont_break", "cont_continue", "func_call", 
		"func_define", "var_define", "var_set", "var_inst", "for_object", "for_repeat", 
		"for_range", "expression", "object", "objItem", "array", "identifier", 
		"iden_seg", "iden_seg_text", "iden_seg_expr", "func_expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'('", "')'", "'{'", "'}'", "','", "':'", "'in'", "'!'", 
		"'.'", "'null'", "'?'", "'['", "']'", "'if'", "'else'", "'for'", "'at'", 
		"'add'", "'do'", "'from'", "'to'", "'per'", "'while'", "'return'", "'break'", 
		"'continue'", "'function'", "'type'", "'var'", "'const'", null, null, 
		null, null, null, null, null, "'+'", "'-'", "'*'", "'/'", "'^'", "'='", 
		"'++'", "'--'", "'+='", "'-='", "'*='", "'/='", "'^='", "'=='", "'!='", 
		"'>'", "'<'", "'>='", "'<='", "'&&'", "'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "CONT_IF", "CONT_ELSE", "CONT_FOR", "CONT_FOR_AT", "CONT_FOR_ADD", 
		"CONT_FOR_REP", "CONT_FOR_FROM", "CONT_FOR_TO", "CONT_FOR_PER", "CONT_WHILE", 
		"CONT_RETURN", "CONT_BREAK", "CONT_CONTINUE", "OBJ_FUNCTION", "OBJ_TYPE", 
		"OBJ_VAR", "OBJ_CONST", "NUMBER", "STRING", "BOOLEAN", "ID", "MUL_DIV", 
		"ADD_SUB", "COMPARE", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", "EXPONENT", 
		"EQUALS", "INCREMENT", "DECREMENT", "ADD_DIRECT", "SUB_DIRECT", "MULT_DIRECT", 
		"DIV_DIRECT", "EXPO_DIRECT", "COND_EQUAL", "COND_NOTEQUAL", "COND_GREATERTHAN", 
		"COND_LESSTHAN", "COND_GREATEROREQUAL", "COND_LESSOREQUAL", "COND_AND", 
		"COND_OR", "WS", "LINE_COMMENT", "MULTILINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "VoxScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static VoxScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public VoxScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public VoxScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			actionSet();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionSetContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext[] action() {
			return GetRuleContexts<ActionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action(int i) {
			return GetRuleContext<ActionContext>(i);
		}
		public ActionSetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionSet; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterActionSet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitActionSet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionSet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionSetContext actionSet() {
		ActionSetContext _localctx = new ActionSetContext(Context, State);
		EnterRule(_localctx, 2, RULE_actionSet);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 38101221376L) != 0)) {
				{
				{
				State = 56;
				action();
				State = 60;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__0) {
					{
					{
					State = 57;
					Match(T__0);
					}
					}
					State = 62;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 67;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Cont_ifContext cont_if() {
			return GetRuleContext<Cont_ifContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_whileContext cont_while() {
			return GetRuleContext<Cont_whileContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_forContext cont_for() {
			return GetRuleContext<Cont_forContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_returnContext cont_return() {
			return GetRuleContext<Cont_returnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_breakContext cont_break() {
			return GetRuleContext<Cont_breakContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_continueContext cont_continue() {
			return GetRuleContext<Cont_continueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defineContext func_define() {
			return GetRuleContext<Func_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_defineContext var_define() {
			return GetRuleContext<Var_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_setContext var_set() {
			return GetRuleContext<Var_setContext>(0);
		}
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterAction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitAction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 4, RULE_action);
		try {
			State = 78;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68;
				cont_if();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 69;
				cont_while();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 70;
				cont_for();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 71;
				cont_return();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 72;
				cont_break();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 73;
				cont_continue();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 74;
				func_call();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 75;
				func_define();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 76;
				var_define();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 77;
				var_set();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_ifContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_IF() { return GetToken(VoxScriptParser.CONT_IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_elseContext cont_else() {
			return GetRuleContext<Cont_elseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_ifContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_if; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_if(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_ifContext cont_if() {
		Cont_ifContext _localctx = new Cont_ifContext(Context, State);
		EnterRule(_localctx, 6, RULE_cont_if);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			Match(CONT_IF);
			State = 81;
			Match(T__1);
			State = 82;
			expression(0);
			State = 83;
			Match(T__2);
			State = 90;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 84;
				Match(T__3);
				State = 86;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
				case 1:
					{
					State = 85;
					actionSet();
					}
					break;
				}
				State = 88;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 89;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 93;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				{
				State = 92;
				cont_else();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_elseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_ELSE() { return GetToken(VoxScriptParser.CONT_ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_elseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_else; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_else(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_elseContext cont_else() {
		Cont_elseContext _localctx = new Cont_elseContext(Context, State);
		EnterRule(_localctx, 8, RULE_cont_else);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95;
			Match(CONT_ELSE);
			State = 102;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 96;
				Match(T__3);
				State = 98;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 97;
					actionSet();
					}
					break;
				}
				State = 100;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 101;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_whileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_WHILE() { return GetToken(VoxScriptParser.CONT_WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_whileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_while; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_while(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_whileContext cont_while() {
		Cont_whileContext _localctx = new Cont_whileContext(Context, State);
		EnterRule(_localctx, 10, RULE_cont_while);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(CONT_WHILE);
			State = 105;
			Match(T__1);
			State = 106;
			expression(0);
			State = 107;
			Match(T__2);
			State = 114;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 108;
				Match(T__3);
				State = 110;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
				case 1:
					{
					State = 109;
					actionSet();
					}
					break;
				}
				State = 112;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 113;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_forContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR() { return GetToken(VoxScriptParser.CONT_FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public For_objectContext for_object() {
			return GetRuleContext<For_objectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_repeatContext for_repeat() {
			return GetRuleContext<For_repeatContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_rangeContext for_range() {
			return GetRuleContext<For_rangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_forContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_for; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_for(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_forContext cont_for() {
		Cont_forContext _localctx = new Cont_forContext(Context, State);
		EnterRule(_localctx, 12, RULE_cont_for);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116;
			Match(CONT_FOR);
			State = 117;
			Match(T__1);
			State = 121;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 118;
				for_object();
				}
				break;
			case 2:
				{
				State = 119;
				for_repeat();
				}
				break;
			case 3:
				{
				State = 120;
				for_range();
				}
				break;
			}
			State = 123;
			Match(T__2);
			State = 130;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 124;
				Match(T__3);
				State = 126;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
				case 1:
					{
					State = 125;
					actionSet();
					}
					break;
				}
				State = 128;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 129;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_returnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_RETURN() { return GetToken(VoxScriptParser.CONT_RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Cont_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_return(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_returnContext cont_return() {
		Cont_returnContext _localctx = new Cont_returnContext(Context, State);
		EnterRule(_localctx, 14, RULE_cont_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			Match(CONT_RETURN);
			State = 134;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 133;
				expression(0);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_breakContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_BREAK() { return GetToken(VoxScriptParser.CONT_BREAK, 0); }
		public Cont_breakContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_break; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_break(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_breakContext cont_break() {
		Cont_breakContext _localctx = new Cont_breakContext(Context, State);
		EnterRule(_localctx, 16, RULE_cont_break);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 136;
			Match(CONT_BREAK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_continueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_CONTINUE() { return GetToken(VoxScriptParser.CONT_CONTINUE, 0); }
		public Cont_continueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_continue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_continue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_continueContext cont_continue() {
		Cont_continueContext _localctx = new Cont_continueContext(Context, State);
		EnterRule(_localctx, 18, RULE_cont_continue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			Match(CONT_CONTINUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Func_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_call(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_callContext func_call() {
		Func_callContext _localctx = new Func_callContext(Context, State);
		EnterRule(_localctx, 20, RULE_func_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 140;
			identifier();
			State = 141;
			Match(T__1);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1164204583444L) != 0)) {
				{
				State = 142;
				expression(0);
				State = 147;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 143;
					Match(T__5);
					State = 144;
					expression(0);
					}
					}
					State = 149;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 152;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_FUNCTION() { return GetToken(VoxScriptParser.OBJ_FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Func_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_defineContext func_define() {
		Func_defineContext _localctx = new Func_defineContext(Context, State);
		EnterRule(_localctx, 22, RULE_func_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 154;
			Match(OBJ_FUNCTION);
			State = 155;
			identifier();
			State = 156;
			Match(T__1);
			State = 165;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 157;
				var_inst();
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 158;
					Match(T__5);
					State = 159;
					var_inst();
					}
					}
					State = 164;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 167;
			Match(T__2);
			State = 174;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 168;
				Match(T__3);
				State = 170;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
				case 1:
					{
					State = 169;
					actionSet();
					}
					break;
				}
				State = 172;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 173;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst() {
			return GetRuleContext<Var_instContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_VAR() { return GetToken(VoxScriptParser.OBJ_VAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_CONST() { return GetToken(VoxScriptParser.OBJ_CONST, 0); }
		public Var_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_defineContext var_define() {
		Var_defineContext _localctx = new Var_defineContext(Context, State);
		EnterRule(_localctx, 24, RULE_var_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			_la = TokenStream.LA(1);
			if ( !(_la==OBJ_VAR || _la==OBJ_CONST) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 177;
			var_inst();
			State = 178;
			Match(EQUALS);
			State = 179;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_setContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Var_setContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_set; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_set(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_set(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_set(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_setContext var_set() {
		Var_setContext _localctx = new Var_setContext(Context, State);
		EnterRule(_localctx, 26, RULE_var_set);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181;
			identifier();
			State = 182;
			Match(EQUALS);
			State = 183;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_instContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		public Var_instContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_inst; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_inst(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_instContext var_inst() {
		Var_instContext _localctx = new Var_instContext(Context, State);
		EnterRule(_localctx, 28, RULE_var_inst);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			identifier();
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 186;
				Match(T__6);
				State = 187;
				identifier();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_objectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public For_objectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_object(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_object(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_object(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_objectContext for_object() {
		For_objectContext _localctx = new For_objectContext(Context, State);
		EnterRule(_localctx, 30, RULE_for_object);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 190;
			identifier();
			State = 191;
			Match(T__5);
			State = 192;
			identifier();
			State = 193;
			Match(T__7);
			State = 194;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_repeatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_AT() { return GetToken(VoxScriptParser.CONT_FOR_AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_REP() { return GetToken(VoxScriptParser.CONT_FOR_REP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_ADD() { return GetToken(VoxScriptParser.CONT_FOR_ADD, 0); }
		public For_repeatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_repeat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_repeat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_repeat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_repeat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_repeatContext for_repeat() {
		For_repeatContext _localctx = new For_repeatContext(Context, State);
		EnterRule(_localctx, 32, RULE_for_repeat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 196;
			identifier();
			State = 197;
			Match(CONT_FOR_AT);
			State = 198;
			expression(0);
			State = 199;
			Match(CONT_FOR_REP);
			State = 200;
			expression(0);
			State = 201;
			Match(CONT_FOR_ADD);
			State = 202;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_rangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_FROM() { return GetToken(VoxScriptParser.CONT_FOR_FROM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_TO() { return GetToken(VoxScriptParser.CONT_FOR_TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_PER() { return GetToken(VoxScriptParser.CONT_FOR_PER, 0); }
		public For_rangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_range; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_range(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_range(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_range(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_rangeContext for_range() {
		For_rangeContext _localctx = new For_rangeContext(Context, State);
		EnterRule(_localctx, 34, RULE_for_range);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			identifier();
			State = 205;
			Match(CONT_FOR_FROM);
			State = 206;
			expression(0);
			State = 207;
			Match(CONT_FOR_TO);
			State = 208;
			expression(0);
			State = 209;
			Match(CONT_FOR_PER);
			State = 210;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext left;
		public ExpressionContext condition;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext primary;
		public ExpressionContext secondary;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(VoxScriptParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(VoxScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(VoxScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(VoxScriptParser.BOOLEAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_exprContext func_expr() {
			return GetRuleContext<Func_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPONENT() { return GetToken(VoxScriptParser.EXPONENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_DIV() { return GetToken(VoxScriptParser.MUL_DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADD_SUB() { return GetToken(VoxScriptParser.ADD_SUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_AND() { return GetToken(VoxScriptParser.COND_AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_OR() { return GetToken(VoxScriptParser.COND_OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMPARE() { return GetToken(VoxScriptParser.COMPARE, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 36;
		EnterRecursionRule(_localctx, 36, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				{
				State = 213;
				Match(T__1);
				State = 214;
				expression(0);
				State = 215;
				Match(T__2);
				}
				break;
			case 2:
				{
				State = 217;
				Match(T__8);
				State = 218;
				expression(19);
				}
				break;
			case 3:
				{
				State = 219;
				Match(MINUS);
				State = 220;
				expression(18);
				}
				break;
			case 4:
				{
				State = 221;
				identifier();
				}
				break;
			case 5:
				{
				State = 222;
				Match(NUMBER);
				}
				break;
			case 6:
				{
				State = 223;
				Match(STRING);
				}
				break;
			case 7:
				{
				State = 224;
				Match(BOOLEAN);
				}
				break;
			case 8:
				{
				State = 225;
				@object();
				}
				break;
			case 9:
				{
				State = 226;
				array();
				}
				break;
			case 10:
				{
				State = 227;
				Match(T__10);
				}
				break;
			case 11:
				{
				State = 228;
				func_expr();
				}
				break;
			case 12:
				{
				State = 229;
				func_call();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 261;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 259;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
					case 1:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 232;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 233;
						_localctx.op = Match(EXPONENT);
						State = 234;
						_localctx.right = expression(18);
						}
						break;
					case 2:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 235;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 236;
						_localctx.op = Match(MUL_DIV);
						State = 237;
						_localctx.right = expression(17);
						}
						break;
					case 3:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 238;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 239;
						_localctx.op = Match(ADD_SUB);
						State = 240;
						_localctx.right = expression(16);
						}
						break;
					case 4:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 241;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 242;
						_localctx.op = Match(COND_AND);
						State = 243;
						_localctx.right = expression(15);
						}
						break;
					case 5:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 244;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 245;
						_localctx.op = Match(COND_OR);
						State = 246;
						_localctx.right = expression(14);
						}
						break;
					case 6:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 247;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 248;
						_localctx.op = Match(COMPARE);
						State = 249;
						_localctx.right = expression(13);
						}
						break;
					case 7:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.condition = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 250;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 251;
						Match(T__11);
						State = 252;
						_localctx.primary = expression(0);
						State = 253;
						Match(T__6);
						State = 254;
						_localctx.secondary = expression(4);
						}
						break;
					case 8:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 256;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						{
						State = 257;
						Match(T__9);
						State = 258;
						identifier();
						}
						}
						break;
					}
					} 
				}
				State = 263;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ObjItemContext[] objItem() {
			return GetRuleContexts<ObjItemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjItemContext objItem(int i) {
			return GetRuleContext<ObjItemContext>(i);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 38, RULE_object);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 264;
			Match(T__3);
			{
			State = 265;
			objItem();
			State = 270;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 266;
				Match(T__5);
				State = 267;
				objItem();
				}
				}
				State = 272;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			State = 273;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjItemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		public ObjItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objItem; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterObjItem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitObjItem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjItemContext objItem() {
		ObjItemContext _localctx = new ObjItemContext(Context, State);
		EnterRule(_localctx, 40, RULE_objItem);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 275;
			expression(0);
			State = 276;
			Match(EQUALS);
			State = 277;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 42, RULE_array);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			Match(T__12);
			State = 288;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1164204583444L) != 0)) {
				{
				State = 280;
				expression(0);
				State = 285;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 281;
					Match(T__5);
					State = 282;
					expression(0);
					}
					}
					State = 287;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 290;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Iden_segContext[] iden_seg() {
			return GetRuleContexts<Iden_segContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Iden_segContext iden_seg(int i) {
			return GetRuleContext<Iden_segContext>(i);
		}
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 44, RULE_identifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 292;
			Match(ID);
			State = 296;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 293;
					iden_seg();
					}
					} 
				}
				State = 298;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_segContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Iden_seg_textContext iden_seg_text() {
			return GetRuleContext<Iden_seg_textContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Iden_seg_exprContext iden_seg_expr() {
			return GetRuleContext<Iden_seg_exprContext>(0);
		}
		public Iden_segContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_segContext iden_seg() {
		Iden_segContext _localctx = new Iden_segContext(Context, State);
		EnterRule(_localctx, 46, RULE_iden_seg);
		try {
			State = 301;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__9:
				EnterOuterAlt(_localctx, 1);
				{
				State = 299;
				iden_seg_text();
				}
				break;
			case T__12:
				EnterOuterAlt(_localctx, 2);
				{
				State = 300;
				iden_seg_expr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_seg_textContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		public Iden_seg_textContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg_text(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg_text(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg_text(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_seg_textContext iden_seg_text() {
		Iden_seg_textContext _localctx = new Iden_seg_textContext(Context, State);
		EnterRule(_localctx, 48, RULE_iden_seg_text);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 303;
			Match(T__9);
			State = 304;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_seg_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Iden_seg_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_seg_exprContext iden_seg_expr() {
		Iden_seg_exprContext _localctx = new Iden_seg_exprContext(Context, State);
		EnterRule(_localctx, 50, RULE_iden_seg_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 306;
			Match(T__12);
			State = 307;
			expression(0);
			State = 308;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_FUNCTION() { return GetToken(VoxScriptParser.OBJ_FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Func_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_exprContext func_expr() {
		Func_exprContext _localctx = new Func_exprContext(Context, State);
		EnterRule(_localctx, 52, RULE_func_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 310;
			Match(OBJ_FUNCTION);
			State = 311;
			Match(T__1);
			State = 320;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 312;
				var_inst();
				State = 317;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 313;
					Match(T__5);
					State = 314;
					var_inst();
					}
					}
					State = 319;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 322;
			Match(T__2);
			State = 323;
			Match(T__3);
			State = 325;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				{
				State = 324;
				actionSet();
				}
				break;
			}
			State = 327;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 18: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 17);
		case 1: return Precpred(Context, 16);
		case 2: return Precpred(Context, 15);
		case 3: return Precpred(Context, 14);
		case 4: return Precpred(Context, 13);
		case 5: return Precpred(Context, 12);
		case 6: return Precpred(Context, 3);
		case 7: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,62,330,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,1,0,1,0,1,1,1,1,5,1,
		59,8,1,10,1,12,1,62,9,1,5,1,64,8,1,10,1,12,1,67,9,1,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,3,2,79,8,2,1,3,1,3,1,3,1,3,1,3,1,3,3,3,87,8,3,1,
		3,1,3,3,3,91,8,3,1,3,3,3,94,8,3,1,4,1,4,1,4,3,4,99,8,4,1,4,1,4,3,4,103,
		8,4,1,5,1,5,1,5,1,5,1,5,1,5,3,5,111,8,5,1,5,1,5,3,5,115,8,5,1,6,1,6,1,
		6,1,6,1,6,3,6,122,8,6,1,6,1,6,1,6,3,6,127,8,6,1,6,1,6,3,6,131,8,6,1,7,
		1,7,3,7,135,8,7,1,8,1,8,1,9,1,9,1,10,1,10,1,10,1,10,1,10,5,10,146,8,10,
		10,10,12,10,149,9,10,3,10,151,8,10,1,10,1,10,1,11,1,11,1,11,1,11,1,11,
		1,11,5,11,161,8,11,10,11,12,11,164,9,11,3,11,166,8,11,1,11,1,11,1,11,3,
		11,171,8,11,1,11,1,11,3,11,175,8,11,1,12,1,12,1,12,1,12,1,12,1,13,1,13,
		1,13,1,13,1,14,1,14,1,14,3,14,189,8,14,1,15,1,15,1,15,1,15,1,15,1,15,1,
		16,1,16,1,16,1,16,1,16,1,16,1,16,1,16,1,17,1,17,1,17,1,17,1,17,1,17,1,
		17,1,17,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,
		18,1,18,1,18,1,18,1,18,1,18,3,18,231,8,18,1,18,1,18,1,18,1,18,1,18,1,18,
		1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,1,18,
		1,18,1,18,1,18,1,18,1,18,1,18,1,18,5,18,260,8,18,10,18,12,18,263,9,18,
		1,19,1,19,1,19,1,19,5,19,269,8,19,10,19,12,19,272,9,19,1,19,1,19,1,20,
		1,20,1,20,1,20,1,21,1,21,1,21,1,21,5,21,284,8,21,10,21,12,21,287,9,21,
		3,21,289,8,21,1,21,1,21,1,22,1,22,5,22,295,8,22,10,22,12,22,298,9,22,1,
		23,1,23,3,23,302,8,23,1,24,1,24,1,24,1,25,1,25,1,25,1,25,1,26,1,26,1,26,
		1,26,1,26,5,26,316,8,26,10,26,12,26,319,9,26,3,26,321,8,26,1,26,1,26,1,
		26,3,26,326,8,26,1,26,1,26,1,26,0,1,36,27,0,2,4,6,8,10,12,14,16,18,20,
		22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,0,1,1,0,30,31,359,0,54,
		1,0,0,0,2,65,1,0,0,0,4,78,1,0,0,0,6,80,1,0,0,0,8,95,1,0,0,0,10,104,1,0,
		0,0,12,116,1,0,0,0,14,132,1,0,0,0,16,136,1,0,0,0,18,138,1,0,0,0,20,140,
		1,0,0,0,22,154,1,0,0,0,24,176,1,0,0,0,26,181,1,0,0,0,28,185,1,0,0,0,30,
		190,1,0,0,0,32,196,1,0,0,0,34,204,1,0,0,0,36,230,1,0,0,0,38,264,1,0,0,
		0,40,275,1,0,0,0,42,279,1,0,0,0,44,292,1,0,0,0,46,301,1,0,0,0,48,303,1,
		0,0,0,50,306,1,0,0,0,52,310,1,0,0,0,54,55,3,2,1,0,55,1,1,0,0,0,56,60,3,
		4,2,0,57,59,5,1,0,0,58,57,1,0,0,0,59,62,1,0,0,0,60,58,1,0,0,0,60,61,1,
		0,0,0,61,64,1,0,0,0,62,60,1,0,0,0,63,56,1,0,0,0,64,67,1,0,0,0,65,63,1,
		0,0,0,65,66,1,0,0,0,66,3,1,0,0,0,67,65,1,0,0,0,68,79,3,6,3,0,69,79,3,10,
		5,0,70,79,3,12,6,0,71,79,3,14,7,0,72,79,3,16,8,0,73,79,3,18,9,0,74,79,
		3,20,10,0,75,79,3,22,11,0,76,79,3,24,12,0,77,79,3,26,13,0,78,68,1,0,0,
		0,78,69,1,0,0,0,78,70,1,0,0,0,78,71,1,0,0,0,78,72,1,0,0,0,78,73,1,0,0,
		0,78,74,1,0,0,0,78,75,1,0,0,0,78,76,1,0,0,0,78,77,1,0,0,0,79,5,1,0,0,0,
		80,81,5,15,0,0,81,82,5,2,0,0,82,83,3,36,18,0,83,90,5,3,0,0,84,86,5,4,0,
		0,85,87,3,2,1,0,86,85,1,0,0,0,86,87,1,0,0,0,87,88,1,0,0,0,88,91,5,5,0,
		0,89,91,3,4,2,0,90,84,1,0,0,0,90,89,1,0,0,0,91,93,1,0,0,0,92,94,3,8,4,
		0,93,92,1,0,0,0,93,94,1,0,0,0,94,7,1,0,0,0,95,102,5,16,0,0,96,98,5,4,0,
		0,97,99,3,2,1,0,98,97,1,0,0,0,98,99,1,0,0,0,99,100,1,0,0,0,100,103,5,5,
		0,0,101,103,3,4,2,0,102,96,1,0,0,0,102,101,1,0,0,0,103,9,1,0,0,0,104,105,
		5,24,0,0,105,106,5,2,0,0,106,107,3,36,18,0,107,114,5,3,0,0,108,110,5,4,
		0,0,109,111,3,2,1,0,110,109,1,0,0,0,110,111,1,0,0,0,111,112,1,0,0,0,112,
		115,5,5,0,0,113,115,3,4,2,0,114,108,1,0,0,0,114,113,1,0,0,0,115,11,1,0,
		0,0,116,117,5,17,0,0,117,121,5,2,0,0,118,122,3,30,15,0,119,122,3,32,16,
		0,120,122,3,34,17,0,121,118,1,0,0,0,121,119,1,0,0,0,121,120,1,0,0,0,122,
		123,1,0,0,0,123,130,5,3,0,0,124,126,5,4,0,0,125,127,3,2,1,0,126,125,1,
		0,0,0,126,127,1,0,0,0,127,128,1,0,0,0,128,131,5,5,0,0,129,131,3,4,2,0,
		130,124,1,0,0,0,130,129,1,0,0,0,131,13,1,0,0,0,132,134,5,25,0,0,133,135,
		3,36,18,0,134,133,1,0,0,0,134,135,1,0,0,0,135,15,1,0,0,0,136,137,5,26,
		0,0,137,17,1,0,0,0,138,139,5,27,0,0,139,19,1,0,0,0,140,141,3,44,22,0,141,
		150,5,2,0,0,142,147,3,36,18,0,143,144,5,6,0,0,144,146,3,36,18,0,145,143,
		1,0,0,0,146,149,1,0,0,0,147,145,1,0,0,0,147,148,1,0,0,0,148,151,1,0,0,
		0,149,147,1,0,0,0,150,142,1,0,0,0,150,151,1,0,0,0,151,152,1,0,0,0,152,
		153,5,3,0,0,153,21,1,0,0,0,154,155,5,28,0,0,155,156,3,44,22,0,156,165,
		5,2,0,0,157,162,3,28,14,0,158,159,5,6,0,0,159,161,3,28,14,0,160,158,1,
		0,0,0,161,164,1,0,0,0,162,160,1,0,0,0,162,163,1,0,0,0,163,166,1,0,0,0,
		164,162,1,0,0,0,165,157,1,0,0,0,165,166,1,0,0,0,166,167,1,0,0,0,167,174,
		5,3,0,0,168,170,5,4,0,0,169,171,3,2,1,0,170,169,1,0,0,0,170,171,1,0,0,
		0,171,172,1,0,0,0,172,175,5,5,0,0,173,175,3,4,2,0,174,168,1,0,0,0,174,
		173,1,0,0,0,175,23,1,0,0,0,176,177,7,0,0,0,177,178,3,28,14,0,178,179,5,
		44,0,0,179,180,3,36,18,0,180,25,1,0,0,0,181,182,3,44,22,0,182,183,5,44,
		0,0,183,184,3,36,18,0,184,27,1,0,0,0,185,188,3,44,22,0,186,187,5,7,0,0,
		187,189,3,44,22,0,188,186,1,0,0,0,188,189,1,0,0,0,189,29,1,0,0,0,190,191,
		3,44,22,0,191,192,5,6,0,0,192,193,3,44,22,0,193,194,5,8,0,0,194,195,3,
		36,18,0,195,31,1,0,0,0,196,197,3,44,22,0,197,198,5,18,0,0,198,199,3,36,
		18,0,199,200,5,20,0,0,200,201,3,36,18,0,201,202,5,19,0,0,202,203,3,36,
		18,0,203,33,1,0,0,0,204,205,3,44,22,0,205,206,5,21,0,0,206,207,3,36,18,
		0,207,208,5,22,0,0,208,209,3,36,18,0,209,210,5,23,0,0,210,211,3,36,18,
		0,211,35,1,0,0,0,212,213,6,18,-1,0,213,214,5,2,0,0,214,215,3,36,18,0,215,
		216,5,3,0,0,216,231,1,0,0,0,217,218,5,9,0,0,218,231,3,36,18,19,219,220,
		5,40,0,0,220,231,3,36,18,18,221,231,3,44,22,0,222,231,5,32,0,0,223,231,
		5,33,0,0,224,231,5,34,0,0,225,231,3,38,19,0,226,231,3,42,21,0,227,231,
		5,11,0,0,228,231,3,52,26,0,229,231,3,20,10,0,230,212,1,0,0,0,230,217,1,
		0,0,0,230,219,1,0,0,0,230,221,1,0,0,0,230,222,1,0,0,0,230,223,1,0,0,0,
		230,224,1,0,0,0,230,225,1,0,0,0,230,226,1,0,0,0,230,227,1,0,0,0,230,228,
		1,0,0,0,230,229,1,0,0,0,231,261,1,0,0,0,232,233,10,17,0,0,233,234,5,43,
		0,0,234,260,3,36,18,18,235,236,10,16,0,0,236,237,5,36,0,0,237,260,3,36,
		18,17,238,239,10,15,0,0,239,240,5,37,0,0,240,260,3,36,18,16,241,242,10,
		14,0,0,242,243,5,58,0,0,243,260,3,36,18,15,244,245,10,13,0,0,245,246,5,
		59,0,0,246,260,3,36,18,14,247,248,10,12,0,0,248,249,5,38,0,0,249,260,3,
		36,18,13,250,251,10,3,0,0,251,252,5,12,0,0,252,253,3,36,18,0,253,254,5,
		7,0,0,254,255,3,36,18,4,255,260,1,0,0,0,256,257,10,5,0,0,257,258,5,10,
		0,0,258,260,3,44,22,0,259,232,1,0,0,0,259,235,1,0,0,0,259,238,1,0,0,0,
		259,241,1,0,0,0,259,244,1,0,0,0,259,247,1,0,0,0,259,250,1,0,0,0,259,256,
		1,0,0,0,260,263,1,0,0,0,261,259,1,0,0,0,261,262,1,0,0,0,262,37,1,0,0,0,
		263,261,1,0,0,0,264,265,5,4,0,0,265,270,3,40,20,0,266,267,5,6,0,0,267,
		269,3,40,20,0,268,266,1,0,0,0,269,272,1,0,0,0,270,268,1,0,0,0,270,271,
		1,0,0,0,271,273,1,0,0,0,272,270,1,0,0,0,273,274,5,5,0,0,274,39,1,0,0,0,
		275,276,3,36,18,0,276,277,5,44,0,0,277,278,3,36,18,0,278,41,1,0,0,0,279,
		288,5,13,0,0,280,285,3,36,18,0,281,282,5,6,0,0,282,284,3,36,18,0,283,281,
		1,0,0,0,284,287,1,0,0,0,285,283,1,0,0,0,285,286,1,0,0,0,286,289,1,0,0,
		0,287,285,1,0,0,0,288,280,1,0,0,0,288,289,1,0,0,0,289,290,1,0,0,0,290,
		291,5,14,0,0,291,43,1,0,0,0,292,296,5,35,0,0,293,295,3,46,23,0,294,293,
		1,0,0,0,295,298,1,0,0,0,296,294,1,0,0,0,296,297,1,0,0,0,297,45,1,0,0,0,
		298,296,1,0,0,0,299,302,3,48,24,0,300,302,3,50,25,0,301,299,1,0,0,0,301,
		300,1,0,0,0,302,47,1,0,0,0,303,304,5,10,0,0,304,305,5,35,0,0,305,49,1,
		0,0,0,306,307,5,13,0,0,307,308,3,36,18,0,308,309,5,14,0,0,309,51,1,0,0,
		0,310,311,5,28,0,0,311,320,5,2,0,0,312,317,3,28,14,0,313,314,5,6,0,0,314,
		316,3,28,14,0,315,313,1,0,0,0,316,319,1,0,0,0,317,315,1,0,0,0,317,318,
		1,0,0,0,318,321,1,0,0,0,319,317,1,0,0,0,320,312,1,0,0,0,320,321,1,0,0,
		0,321,322,1,0,0,0,322,323,5,3,0,0,323,325,5,4,0,0,324,326,3,2,1,0,325,
		324,1,0,0,0,325,326,1,0,0,0,326,327,1,0,0,0,327,328,5,5,0,0,328,53,1,0,
		0,0,32,60,65,78,86,90,93,98,102,110,114,121,126,130,134,147,150,162,165,
		170,174,188,230,259,261,270,285,288,296,301,317,320,325
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
