//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class VoxScriptParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, CONT_IF=15, CONT_ELSE=16, 
		CONT_FOR=17, CONT_FOR_AT=18, CONT_FOR_ADD=19, CONT_FOR_REP=20, CONT_FOR_FROM=21, 
		CONT_FOR_TO=22, CONT_FOR_PER=23, CONT_WHILE=24, CONT_RETURN=25, CONT_BREAK=26, 
		CONT_CONTINUE=27, OBJ_FUNCTION=28, OBJ_TYPE=29, OBJ_VAR=30, OBJ_CONST=31, 
		NUMBER=32, STRING=33, BOOLEAN=34, ID=35, MUL_DIV=36, ADD_SUB=37, COMPARE=38, 
		ARITH_ASSIGN=39, PLUS=40, MINUS=41, MULTIPLY=42, DIVIDE=43, EXPONENT=44, 
		MODULO=45, EQUALS=46, INCREMENT=47, DECREMENT=48, ADD_DIRECT=49, SUB_DIRECT=50, 
		MULT_DIRECT=51, DIV_DIRECT=52, EXPO_DIRECT=53, MOD_DIRECT=54, COND_EQUAL=55, 
		COND_NOTEQUAL=56, COND_GREATERTHAN=57, COND_LESSTHAN=58, COND_GREATEROREQUAL=59, 
		COND_LESSOREQUAL=60, COND_AND=61, COND_OR=62, WS=63, LINE_COMMENT=64, 
		MULTILINE_COMMENT=65;
	public const int
		RULE_program = 0, RULE_actionSet = 1, RULE_action = 2, RULE_cont_if = 3, 
		RULE_cont_else = 4, RULE_cont_while = 5, RULE_cont_for = 6, RULE_cont_return = 7, 
		RULE_cont_break = 8, RULE_cont_continue = 9, RULE_func_call = 10, RULE_func_define = 11, 
		RULE_var_define = 12, RULE_var_set = 13, RULE_var_arith = 14, RULE_var_incre = 15, 
		RULE_var_inst = 16, RULE_for_object = 17, RULE_for_repeat = 18, RULE_for_range = 19, 
		RULE_expression = 20, RULE_object = 21, RULE_objItem = 22, RULE_array = 23, 
		RULE_identifier = 24, RULE_iden_seg = 25, RULE_iden_seg_text = 26, RULE_iden_seg_expr = 27, 
		RULE_func_expr = 28;
	public static readonly string[] ruleNames = {
		"program", "actionSet", "action", "cont_if", "cont_else", "cont_while", 
		"cont_for", "cont_return", "cont_break", "cont_continue", "func_call", 
		"func_define", "var_define", "var_set", "var_arith", "var_incre", "var_inst", 
		"for_object", "for_repeat", "for_range", "expression", "object", "objItem", 
		"array", "identifier", "iden_seg", "iden_seg_text", "iden_seg_expr", "func_expr"
	};

	private static readonly string[] _LiteralNames = {
		null, "';'", "'('", "')'", "'{'", "'}'", "','", "':'", "'in'", "'!'", 
		"'.'", "'null'", "'?'", "'['", "']'", "'if'", "'else'", "'for'", "'at'", 
		"'add'", "'do'", "'from'", "'to'", "'per'", "'while'", "'return'", "'break'", 
		"'continue'", "'function'", "'type'", "'var'", "'const'", null, null, 
		null, null, null, null, null, null, "'+'", "'-'", "'*'", "'/'", "'^'", 
		"'%'", "'='", "'++'", "'--'", "'+='", "'-='", "'*='", "'/='", "'^='", 
		"'%='", "'=='", "'!='", "'>'", "'<'", "'>='", "'<='", "'&&'", "'||'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "CONT_IF", "CONT_ELSE", "CONT_FOR", "CONT_FOR_AT", "CONT_FOR_ADD", 
		"CONT_FOR_REP", "CONT_FOR_FROM", "CONT_FOR_TO", "CONT_FOR_PER", "CONT_WHILE", 
		"CONT_RETURN", "CONT_BREAK", "CONT_CONTINUE", "OBJ_FUNCTION", "OBJ_TYPE", 
		"OBJ_VAR", "OBJ_CONST", "NUMBER", "STRING", "BOOLEAN", "ID", "MUL_DIV", 
		"ADD_SUB", "COMPARE", "ARITH_ASSIGN", "PLUS", "MINUS", "MULTIPLY", "DIVIDE", 
		"EXPONENT", "MODULO", "EQUALS", "INCREMENT", "DECREMENT", "ADD_DIRECT", 
		"SUB_DIRECT", "MULT_DIRECT", "DIV_DIRECT", "EXPO_DIRECT", "MOD_DIRECT", 
		"COND_EQUAL", "COND_NOTEQUAL", "COND_GREATERTHAN", "COND_LESSTHAN", "COND_GREATEROREQUAL", 
		"COND_LESSOREQUAL", "COND_AND", "COND_OR", "WS", "LINE_COMMENT", "MULTILINE_COMMENT"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "VoxScript.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static VoxScriptParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public VoxScriptParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public VoxScriptParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58;
			actionSet();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionSetContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext[] action() {
			return GetRuleContexts<ActionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action(int i) {
			return GetRuleContext<ActionContext>(i);
		}
		public ActionSetContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_actionSet; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterActionSet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitActionSet(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitActionSet(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionSetContext actionSet() {
		ActionSetContext _localctx = new ActionSetContext(Context, State);
		EnterRule(_localctx, 2, RULE_actionSet);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 38101221376L) != 0)) {
				{
				{
				State = 60;
				action();
				State = 64;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__0) {
					{
					{
					State = 61;
					Match(T__0);
					}
					}
					State = 66;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
				}
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ActionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Cont_ifContext cont_if() {
			return GetRuleContext<Cont_ifContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_whileContext cont_while() {
			return GetRuleContext<Cont_whileContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_forContext cont_for() {
			return GetRuleContext<Cont_forContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_returnContext cont_return() {
			return GetRuleContext<Cont_returnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_breakContext cont_break() {
			return GetRuleContext<Cont_breakContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_continueContext cont_continue() {
			return GetRuleContext<Cont_continueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_defineContext func_define() {
			return GetRuleContext<Func_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_defineContext var_define() {
			return GetRuleContext<Var_defineContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_setContext var_set() {
			return GetRuleContext<Var_setContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_arithContext var_arith() {
			return GetRuleContext<Var_arithContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_increContext var_incre() {
			return GetRuleContext<Var_increContext>(0);
		}
		public ActionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_action; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterAction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitAction(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ActionContext action() {
		ActionContext _localctx = new ActionContext(Context, State);
		EnterRule(_localctx, 4, RULE_action);
		try {
			State = 84;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72;
				cont_if();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 73;
				cont_while();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 74;
				cont_for();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 75;
				cont_return();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 76;
				cont_break();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 77;
				cont_continue();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 78;
				func_call();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 79;
				func_define();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 80;
				var_define();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 81;
				var_set();
				}
				break;
			case 11:
				EnterOuterAlt(_localctx, 11);
				{
				State = 82;
				var_arith();
				}
				break;
			case 12:
				EnterOuterAlt(_localctx, 12);
				{
				State = 83;
				var_incre();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_ifContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_IF() { return GetToken(VoxScriptParser.CONT_IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Cont_elseContext cont_else() {
			return GetRuleContext<Cont_elseContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_ifContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_if; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_if(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_if(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_ifContext cont_if() {
		Cont_ifContext _localctx = new Cont_ifContext(Context, State);
		EnterRule(_localctx, 6, RULE_cont_if);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(CONT_IF);
			State = 87;
			Match(T__1);
			State = 88;
			expression(0);
			State = 89;
			Match(T__2);
			State = 96;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 90;
				Match(T__3);
				State = 92;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
				case 1:
					{
					State = 91;
					actionSet();
					}
					break;
				}
				State = 94;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 95;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 99;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				{
				State = 98;
				cont_else();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_elseContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_ELSE() { return GetToken(VoxScriptParser.CONT_ELSE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_elseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_else; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_else(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_else(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_elseContext cont_else() {
		Cont_elseContext _localctx = new Cont_elseContext(Context, State);
		EnterRule(_localctx, 8, RULE_cont_else);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101;
			Match(CONT_ELSE);
			State = 108;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 102;
				Match(T__3);
				State = 104;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
				case 1:
					{
					State = 103;
					actionSet();
					}
					break;
				}
				State = 106;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 107;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_whileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_WHILE() { return GetToken(VoxScriptParser.CONT_WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_whileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_while; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_while(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_while(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_whileContext cont_while() {
		Cont_whileContext _localctx = new Cont_whileContext(Context, State);
		EnterRule(_localctx, 10, RULE_cont_while);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110;
			Match(CONT_WHILE);
			State = 111;
			Match(T__1);
			State = 112;
			expression(0);
			State = 113;
			Match(T__2);
			State = 120;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 114;
				Match(T__3);
				State = 116;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
				case 1:
					{
					State = 115;
					actionSet();
					}
					break;
				}
				State = 118;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 119;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_forContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR() { return GetToken(VoxScriptParser.CONT_FOR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public For_objectContext for_object() {
			return GetRuleContext<For_objectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_repeatContext for_repeat() {
			return GetRuleContext<For_repeatContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public For_rangeContext for_range() {
			return GetRuleContext<For_rangeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Cont_forContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_for; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_for(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_for(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_forContext cont_for() {
		Cont_forContext _localctx = new Cont_forContext(Context, State);
		EnterRule(_localctx, 12, RULE_cont_for);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 122;
			Match(CONT_FOR);
			State = 123;
			Match(T__1);
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				{
				State = 124;
				for_object();
				}
				break;
			case 2:
				{
				State = 125;
				for_repeat();
				}
				break;
			case 3:
				{
				State = 126;
				for_range();
				}
				break;
			}
			State = 129;
			Match(T__2);
			State = 136;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 130;
				Match(T__3);
				State = 132;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,11,Context) ) {
				case 1:
					{
					State = 131;
					actionSet();
					}
					break;
				}
				State = 134;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 135;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_returnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_RETURN() { return GetToken(VoxScriptParser.CONT_RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Cont_returnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_return(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_return(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_returnContext cont_return() {
		Cont_returnContext _localctx = new Cont_returnContext(Context, State);
		EnterRule(_localctx, 14, RULE_cont_return);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138;
			Match(CONT_RETURN);
			State = 140;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 139;
				expression(0);
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_breakContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_BREAK() { return GetToken(VoxScriptParser.CONT_BREAK, 0); }
		public Cont_breakContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_break; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_break(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_break(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_breakContext cont_break() {
		Cont_breakContext _localctx = new Cont_breakContext(Context, State);
		EnterRule(_localctx, 16, RULE_cont_break);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142;
			Match(CONT_BREAK);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Cont_continueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_CONTINUE() { return GetToken(VoxScriptParser.CONT_CONTINUE, 0); }
		public Cont_continueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_cont_continue; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitCont_continue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCont_continue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Cont_continueContext cont_continue() {
		Cont_continueContext _localctx = new Cont_continueContext(Context, State);
		EnterRule(_localctx, 18, RULE_cont_continue);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 144;
			Match(CONT_CONTINUE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_callContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public Func_callContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_call; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_call(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_call(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_callContext func_call() {
		Func_callContext _localctx = new Func_callContext(Context, State);
		EnterRule(_localctx, 20, RULE_func_call);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			identifier();
			State = 147;
			Match(T__1);
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 2263716211220L) != 0)) {
				{
				State = 148;
				expression(0);
				State = 153;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 149;
					Match(T__5);
					State = 150;
					expression(0);
					}
					}
					State = 155;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 158;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_FUNCTION() { return GetToken(VoxScriptParser.OBJ_FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionContext action() {
			return GetRuleContext<ActionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Func_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_defineContext func_define() {
		Func_defineContext _localctx = new Func_defineContext(Context, State);
		EnterRule(_localctx, 22, RULE_func_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160;
			Match(OBJ_FUNCTION);
			State = 161;
			identifier();
			State = 162;
			Match(T__1);
			State = 171;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 163;
				var_inst();
				State = 168;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 164;
					Match(T__5);
					State = 165;
					var_inst();
					}
					}
					State = 170;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 173;
			Match(T__2);
			State = 180;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__3:
				{
				{
				State = 174;
				Match(T__3);
				State = 176;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,18,Context) ) {
				case 1:
					{
					State = 175;
					actionSet();
					}
					break;
				}
				State = 178;
				Match(T__4);
				}
				}
				break;
			case CONT_IF:
			case CONT_FOR:
			case CONT_WHILE:
			case CONT_RETURN:
			case CONT_BREAK:
			case CONT_CONTINUE:
			case OBJ_FUNCTION:
			case OBJ_VAR:
			case OBJ_CONST:
			case ID:
				{
				State = 179;
				action();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_defineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst() {
			return GetRuleContext<Var_instContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_VAR() { return GetToken(VoxScriptParser.OBJ_VAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_CONST() { return GetToken(VoxScriptParser.OBJ_CONST, 0); }
		public Var_defineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_define; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_define(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_define(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_defineContext var_define() {
		Var_defineContext _localctx = new Var_defineContext(Context, State);
		EnterRule(_localctx, 24, RULE_var_define);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 182;
			_la = TokenStream.LA(1);
			if ( !(_la==OBJ_VAR || _la==OBJ_CONST) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 183;
			var_inst();
			State = 184;
			Match(EQUALS);
			State = 185;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_setContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Var_setContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_set; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_set(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_set(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_set(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_setContext var_set() {
		Var_setContext _localctx = new Var_setContext(Context, State);
		EnterRule(_localctx, 26, RULE_var_set);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 187;
			identifier();
			State = 188;
			Match(EQUALS);
			State = 189;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_arithContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARITH_ASSIGN() { return GetToken(VoxScriptParser.ARITH_ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Var_arithContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_arith; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_arith(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_arith(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_arith(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_arithContext var_arith() {
		Var_arithContext _localctx = new Var_arithContext(Context, State);
		EnterRule(_localctx, 28, RULE_var_arith);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 191;
			identifier();
			State = 192;
			Match(ARITH_ASSIGN);
			State = 193;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_increContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INCREMENT() { return GetToken(VoxScriptParser.INCREMENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECREMENT() { return GetToken(VoxScriptParser.DECREMENT, 0); }
		public Var_increContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_incre; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_incre(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_incre(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_incre(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_increContext var_incre() {
		Var_increContext _localctx = new Var_increContext(Context, State);
		EnterRule(_localctx, 30, RULE_var_incre);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 195;
			identifier();
			State = 196;
			_la = TokenStream.LA(1);
			if ( !(_la==INCREMENT || _la==DECREMENT) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Var_instContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		public Var_instContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_var_inst; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitVar_inst(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVar_inst(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Var_instContext var_inst() {
		Var_instContext _localctx = new Var_instContext(Context, State);
		EnterRule(_localctx, 32, RULE_var_inst);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 198;
			identifier();
			State = 201;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__6) {
				{
				State = 199;
				Match(T__6);
				State = 200;
				identifier();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_objectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext[] identifier() {
			return GetRuleContexts<IdentifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier(int i) {
			return GetRuleContext<IdentifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public For_objectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_object(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_object(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_object(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_objectContext for_object() {
		For_objectContext _localctx = new For_objectContext(Context, State);
		EnterRule(_localctx, 34, RULE_for_object);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 203;
			identifier();
			State = 204;
			Match(T__5);
			State = 205;
			identifier();
			State = 206;
			Match(T__7);
			State = 207;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_repeatContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_AT() { return GetToken(VoxScriptParser.CONT_FOR_AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_REP() { return GetToken(VoxScriptParser.CONT_FOR_REP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_ADD() { return GetToken(VoxScriptParser.CONT_FOR_ADD, 0); }
		public For_repeatContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_repeat; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_repeat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_repeat(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_repeat(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_repeatContext for_repeat() {
		For_repeatContext _localctx = new For_repeatContext(Context, State);
		EnterRule(_localctx, 36, RULE_for_repeat);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209;
			identifier();
			State = 210;
			Match(CONT_FOR_AT);
			State = 211;
			expression(0);
			State = 212;
			Match(CONT_FOR_REP);
			State = 213;
			expression(0);
			State = 214;
			Match(CONT_FOR_ADD);
			State = 215;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class For_rangeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_FROM() { return GetToken(VoxScriptParser.CONT_FOR_FROM, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_TO() { return GetToken(VoxScriptParser.CONT_FOR_TO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CONT_FOR_PER() { return GetToken(VoxScriptParser.CONT_FOR_PER, 0); }
		public For_rangeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_for_range; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFor_range(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFor_range(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFor_range(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public For_rangeContext for_range() {
		For_rangeContext _localctx = new For_rangeContext(Context, State);
		EnterRule(_localctx, 38, RULE_for_range);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 217;
			identifier();
			State = 218;
			Match(CONT_FOR_FROM);
			State = 219;
			expression(0);
			State = 220;
			Match(CONT_FOR_TO);
			State = 221;
			expression(0);
			State = 222;
			Match(CONT_FOR_PER);
			State = 223;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext left;
		public ExpressionContext condition;
		public IToken op;
		public ExpressionContext right;
		public ExpressionContext primary;
		public ExpressionContext secondary;
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(VoxScriptParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IdentifierContext identifier() {
			return GetRuleContext<IdentifierContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NUMBER() { return GetToken(VoxScriptParser.NUMBER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(VoxScriptParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN() { return GetToken(VoxScriptParser.BOOLEAN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_exprContext func_expr() {
			return GetRuleContext<Func_exprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Func_callContext func_call() {
			return GetRuleContext<Func_callContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EXPONENT() { return GetToken(VoxScriptParser.EXPONENT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MUL_DIV() { return GetToken(VoxScriptParser.MUL_DIV, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ADD_SUB() { return GetToken(VoxScriptParser.ADD_SUB, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_AND() { return GetToken(VoxScriptParser.COND_AND, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COND_OR() { return GetToken(VoxScriptParser.COND_OR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMPARE() { return GetToken(VoxScriptParser.COMPARE, 0); }
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(Context, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 40;
		EnterRecursionRule(_localctx, 40, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 243;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
			case 1:
				{
				State = 226;
				Match(T__1);
				State = 227;
				expression(0);
				State = 228;
				Match(T__2);
				}
				break;
			case 2:
				{
				State = 230;
				Match(T__8);
				State = 231;
				expression(19);
				}
				break;
			case 3:
				{
				State = 232;
				Match(MINUS);
				State = 233;
				expression(18);
				}
				break;
			case 4:
				{
				State = 234;
				identifier();
				}
				break;
			case 5:
				{
				State = 235;
				Match(NUMBER);
				}
				break;
			case 6:
				{
				State = 236;
				Match(STRING);
				}
				break;
			case 7:
				{
				State = 237;
				Match(BOOLEAN);
				}
				break;
			case 8:
				{
				State = 238;
				@object();
				}
				break;
			case 9:
				{
				State = 239;
				array();
				}
				break;
			case 10:
				{
				State = 240;
				Match(T__10);
				}
				break;
			case 11:
				{
				State = 241;
				func_expr();
				}
				break;
			case 12:
				{
				State = 242;
				func_call();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 274;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 272;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
					case 1:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 245;
						if (!(Precpred(Context, 17))) throw new FailedPredicateException(this, "Precpred(Context, 17)");
						State = 246;
						_localctx.op = Match(EXPONENT);
						State = 247;
						_localctx.right = expression(18);
						}
						break;
					case 2:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 248;
						if (!(Precpred(Context, 16))) throw new FailedPredicateException(this, "Precpred(Context, 16)");
						State = 249;
						_localctx.op = Match(MUL_DIV);
						State = 250;
						_localctx.right = expression(17);
						}
						break;
					case 3:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 251;
						if (!(Precpred(Context, 15))) throw new FailedPredicateException(this, "Precpred(Context, 15)");
						State = 252;
						_localctx.op = Match(ADD_SUB);
						State = 253;
						_localctx.right = expression(16);
						}
						break;
					case 4:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 254;
						if (!(Precpred(Context, 14))) throw new FailedPredicateException(this, "Precpred(Context, 14)");
						State = 255;
						_localctx.op = Match(COND_AND);
						State = 256;
						_localctx.right = expression(15);
						}
						break;
					case 5:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 257;
						if (!(Precpred(Context, 13))) throw new FailedPredicateException(this, "Precpred(Context, 13)");
						State = 258;
						_localctx.op = Match(COND_OR);
						State = 259;
						_localctx.right = expression(14);
						}
						break;
					case 6:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.left = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 260;
						if (!(Precpred(Context, 12))) throw new FailedPredicateException(this, "Precpred(Context, 12)");
						State = 261;
						_localctx.op = Match(COMPARE);
						State = 262;
						_localctx.right = expression(13);
						}
						break;
					case 7:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						_localctx.condition = _prevctx;
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 263;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 264;
						Match(T__11);
						State = 265;
						_localctx.primary = expression(0);
						State = 266;
						Match(T__6);
						State = 267;
						_localctx.secondary = expression(4);
						}
						break;
					case 8:
						{
						_localctx = new ExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expression);
						State = 269;
						if (!(Precpred(Context, 5))) throw new FailedPredicateException(this, "Precpred(Context, 5)");
						{
						State = 270;
						Match(T__9);
						State = 271;
						identifier();
						}
						}
						break;
					}
					} 
				}
				State = 276;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ObjItemContext[] objItem() {
			return GetRuleContexts<ObjItemContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjItemContext objItem(int i) {
			return GetRuleContext<ObjItemContext>(i);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObject(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 42, RULE_object);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 277;
			Match(T__3);
			{
			State = 278;
			objItem();
			State = 283;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__5) {
				{
				{
				State = 279;
				Match(T__5);
				State = 280;
				objItem();
				}
				}
				State = 285;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
			State = 286;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjItemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUALS() { return GetToken(VoxScriptParser.EQUALS, 0); }
		public ObjItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_objItem; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterObjItem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitObjItem(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObjItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjItemContext objItem() {
		ObjItemContext _localctx = new ObjItemContext(Context, State);
		EnterRule(_localctx, 44, RULE_objItem);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 288;
			expression(0);
			State = 289;
			Match(EQUALS);
			State = 290;
			expression(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitArray(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 46, RULE_array);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 292;
			Match(T__12);
			State = 301;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 2263716211220L) != 0)) {
				{
				State = 293;
				expression(0);
				State = 298;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 294;
					Match(T__5);
					State = 295;
					expression(0);
					}
					}
					State = 300;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 303;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Iden_segContext[] iden_seg() {
			return GetRuleContexts<Iden_segContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Iden_segContext iden_seg(int i) {
			return GetRuleContext<Iden_segContext>(i);
		}
		public IdentifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIdentifier(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentifierContext identifier() {
		IdentifierContext _localctx = new IdentifierContext(Context, State);
		EnterRule(_localctx, 48, RULE_identifier);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 305;
			Match(ID);
			State = 309;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 306;
					iden_seg();
					}
					} 
				}
				State = 311;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,27,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_segContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Iden_seg_textContext iden_seg_text() {
			return GetRuleContext<Iden_seg_textContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Iden_seg_exprContext iden_seg_expr() {
			return GetRuleContext<Iden_seg_exprContext>(0);
		}
		public Iden_segContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_segContext iden_seg() {
		Iden_segContext _localctx = new Iden_segContext(Context, State);
		EnterRule(_localctx, 50, RULE_iden_seg);
		try {
			State = 314;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__9:
				EnterOuterAlt(_localctx, 1);
				{
				State = 312;
				iden_seg_text();
				}
				break;
			case T__12:
				EnterOuterAlt(_localctx, 2);
				{
				State = 313;
				iden_seg_expr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_seg_textContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(VoxScriptParser.ID, 0); }
		public Iden_seg_textContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg_text; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg_text(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg_text(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg_text(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_seg_textContext iden_seg_text() {
		Iden_seg_textContext _localctx = new Iden_seg_textContext(Context, State);
		EnterRule(_localctx, 52, RULE_iden_seg_text);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 316;
			Match(T__9);
			State = 317;
			Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Iden_seg_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Iden_seg_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iden_seg_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterIden_seg_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitIden_seg_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIden_seg_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Iden_seg_exprContext iden_seg_expr() {
		Iden_seg_exprContext _localctx = new Iden_seg_exprContext(Context, State);
		EnterRule(_localctx, 54, RULE_iden_seg_expr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 319;
			Match(T__12);
			State = 320;
			expression(0);
			State = 321;
			Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Func_exprContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode OBJ_FUNCTION() { return GetToken(VoxScriptParser.OBJ_FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext[] var_inst() {
			return GetRuleContexts<Var_instContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Var_instContext var_inst(int i) {
			return GetRuleContext<Var_instContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ActionSetContext actionSet() {
			return GetRuleContext<ActionSetContext>(0);
		}
		public Func_exprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_func_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.EnterFunc_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IVoxScriptListener typedListener = listener as IVoxScriptListener;
			if (typedListener != null) typedListener.ExitFunc_expr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IVoxScriptVisitor<TResult> typedVisitor = visitor as IVoxScriptVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunc_expr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Func_exprContext func_expr() {
		Func_exprContext _localctx = new Func_exprContext(Context, State);
		EnterRule(_localctx, 56, RULE_func_expr);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 323;
			Match(OBJ_FUNCTION);
			State = 324;
			Match(T__1);
			State = 333;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ID) {
				{
				State = 325;
				var_inst();
				State = 330;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__5) {
					{
					{
					State = 326;
					Match(T__5);
					State = 327;
					var_inst();
					}
					}
					State = 332;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 335;
			Match(T__2);
			State = 336;
			Match(T__3);
			State = 338;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				{
				State = 337;
				actionSet();
				}
				break;
			}
			State = 340;
			Match(T__4);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 20: return expression_sempred((ExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 17);
		case 1: return Precpred(Context, 16);
		case 2: return Precpred(Context, 15);
		case 3: return Precpred(Context, 14);
		case 4: return Precpred(Context, 13);
		case 5: return Precpred(Context, 12);
		case 6: return Precpred(Context, 3);
		case 7: return Precpred(Context, 5);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,65,343,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,7,28,
		1,0,1,0,1,1,1,1,5,1,63,8,1,10,1,12,1,66,9,1,5,1,68,8,1,10,1,12,1,71,9,
		1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,85,8,2,1,3,1,3,1,
		3,1,3,1,3,1,3,3,3,93,8,3,1,3,1,3,3,3,97,8,3,1,3,3,3,100,8,3,1,4,1,4,1,
		4,3,4,105,8,4,1,4,1,4,3,4,109,8,4,1,5,1,5,1,5,1,5,1,5,1,5,3,5,117,8,5,
		1,5,1,5,3,5,121,8,5,1,6,1,6,1,6,1,6,1,6,3,6,128,8,6,1,6,1,6,1,6,3,6,133,
		8,6,1,6,1,6,3,6,137,8,6,1,7,1,7,3,7,141,8,7,1,8,1,8,1,9,1,9,1,10,1,10,
		1,10,1,10,1,10,5,10,152,8,10,10,10,12,10,155,9,10,3,10,157,8,10,1,10,1,
		10,1,11,1,11,1,11,1,11,1,11,1,11,5,11,167,8,11,10,11,12,11,170,9,11,3,
		11,172,8,11,1,11,1,11,1,11,3,11,177,8,11,1,11,1,11,3,11,181,8,11,1,12,
		1,12,1,12,1,12,1,12,1,13,1,13,1,13,1,13,1,14,1,14,1,14,1,14,1,15,1,15,
		1,15,1,16,1,16,1,16,3,16,202,8,16,1,17,1,17,1,17,1,17,1,17,1,17,1,18,1,
		18,1,18,1,18,1,18,1,18,1,18,1,18,1,19,1,19,1,19,1,19,1,19,1,19,1,19,1,
		19,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,
		20,1,20,1,20,1,20,1,20,3,20,244,8,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,
		1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,1,20,
		1,20,1,20,1,20,1,20,1,20,1,20,5,20,273,8,20,10,20,12,20,276,9,20,1,21,
		1,21,1,21,1,21,5,21,282,8,21,10,21,12,21,285,9,21,1,21,1,21,1,22,1,22,
		1,22,1,22,1,23,1,23,1,23,1,23,5,23,297,8,23,10,23,12,23,300,9,23,3,23,
		302,8,23,1,23,1,23,1,24,1,24,5,24,308,8,24,10,24,12,24,311,9,24,1,25,1,
		25,3,25,315,8,25,1,26,1,26,1,26,1,27,1,27,1,27,1,27,1,28,1,28,1,28,1,28,
		1,28,5,28,329,8,28,10,28,12,28,332,9,28,3,28,334,8,28,1,28,1,28,1,28,3,
		28,339,8,28,1,28,1,28,1,28,0,1,40,29,0,2,4,6,8,10,12,14,16,18,20,22,24,
		26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,0,2,1,0,30,31,1,0,47,48,
		372,0,58,1,0,0,0,2,69,1,0,0,0,4,84,1,0,0,0,6,86,1,0,0,0,8,101,1,0,0,0,
		10,110,1,0,0,0,12,122,1,0,0,0,14,138,1,0,0,0,16,142,1,0,0,0,18,144,1,0,
		0,0,20,146,1,0,0,0,22,160,1,0,0,0,24,182,1,0,0,0,26,187,1,0,0,0,28,191,
		1,0,0,0,30,195,1,0,0,0,32,198,1,0,0,0,34,203,1,0,0,0,36,209,1,0,0,0,38,
		217,1,0,0,0,40,243,1,0,0,0,42,277,1,0,0,0,44,288,1,0,0,0,46,292,1,0,0,
		0,48,305,1,0,0,0,50,314,1,0,0,0,52,316,1,0,0,0,54,319,1,0,0,0,56,323,1,
		0,0,0,58,59,3,2,1,0,59,1,1,0,0,0,60,64,3,4,2,0,61,63,5,1,0,0,62,61,1,0,
		0,0,63,66,1,0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,68,1,0,0,0,66,64,1,0,
		0,0,67,60,1,0,0,0,68,71,1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,3,1,0,0,
		0,71,69,1,0,0,0,72,85,3,6,3,0,73,85,3,10,5,0,74,85,3,12,6,0,75,85,3,14,
		7,0,76,85,3,16,8,0,77,85,3,18,9,0,78,85,3,20,10,0,79,85,3,22,11,0,80,85,
		3,24,12,0,81,85,3,26,13,0,82,85,3,28,14,0,83,85,3,30,15,0,84,72,1,0,0,
		0,84,73,1,0,0,0,84,74,1,0,0,0,84,75,1,0,0,0,84,76,1,0,0,0,84,77,1,0,0,
		0,84,78,1,0,0,0,84,79,1,0,0,0,84,80,1,0,0,0,84,81,1,0,0,0,84,82,1,0,0,
		0,84,83,1,0,0,0,85,5,1,0,0,0,86,87,5,15,0,0,87,88,5,2,0,0,88,89,3,40,20,
		0,89,96,5,3,0,0,90,92,5,4,0,0,91,93,3,2,1,0,92,91,1,0,0,0,92,93,1,0,0,
		0,93,94,1,0,0,0,94,97,5,5,0,0,95,97,3,4,2,0,96,90,1,0,0,0,96,95,1,0,0,
		0,97,99,1,0,0,0,98,100,3,8,4,0,99,98,1,0,0,0,99,100,1,0,0,0,100,7,1,0,
		0,0,101,108,5,16,0,0,102,104,5,4,0,0,103,105,3,2,1,0,104,103,1,0,0,0,104,
		105,1,0,0,0,105,106,1,0,0,0,106,109,5,5,0,0,107,109,3,4,2,0,108,102,1,
		0,0,0,108,107,1,0,0,0,109,9,1,0,0,0,110,111,5,24,0,0,111,112,5,2,0,0,112,
		113,3,40,20,0,113,120,5,3,0,0,114,116,5,4,0,0,115,117,3,2,1,0,116,115,
		1,0,0,0,116,117,1,0,0,0,117,118,1,0,0,0,118,121,5,5,0,0,119,121,3,4,2,
		0,120,114,1,0,0,0,120,119,1,0,0,0,121,11,1,0,0,0,122,123,5,17,0,0,123,
		127,5,2,0,0,124,128,3,34,17,0,125,128,3,36,18,0,126,128,3,38,19,0,127,
		124,1,0,0,0,127,125,1,0,0,0,127,126,1,0,0,0,128,129,1,0,0,0,129,136,5,
		3,0,0,130,132,5,4,0,0,131,133,3,2,1,0,132,131,1,0,0,0,132,133,1,0,0,0,
		133,134,1,0,0,0,134,137,5,5,0,0,135,137,3,4,2,0,136,130,1,0,0,0,136,135,
		1,0,0,0,137,13,1,0,0,0,138,140,5,25,0,0,139,141,3,40,20,0,140,139,1,0,
		0,0,140,141,1,0,0,0,141,15,1,0,0,0,142,143,5,26,0,0,143,17,1,0,0,0,144,
		145,5,27,0,0,145,19,1,0,0,0,146,147,3,48,24,0,147,156,5,2,0,0,148,153,
		3,40,20,0,149,150,5,6,0,0,150,152,3,40,20,0,151,149,1,0,0,0,152,155,1,
		0,0,0,153,151,1,0,0,0,153,154,1,0,0,0,154,157,1,0,0,0,155,153,1,0,0,0,
		156,148,1,0,0,0,156,157,1,0,0,0,157,158,1,0,0,0,158,159,5,3,0,0,159,21,
		1,0,0,0,160,161,5,28,0,0,161,162,3,48,24,0,162,171,5,2,0,0,163,168,3,32,
		16,0,164,165,5,6,0,0,165,167,3,32,16,0,166,164,1,0,0,0,167,170,1,0,0,0,
		168,166,1,0,0,0,168,169,1,0,0,0,169,172,1,0,0,0,170,168,1,0,0,0,171,163,
		1,0,0,0,171,172,1,0,0,0,172,173,1,0,0,0,173,180,5,3,0,0,174,176,5,4,0,
		0,175,177,3,2,1,0,176,175,1,0,0,0,176,177,1,0,0,0,177,178,1,0,0,0,178,
		181,5,5,0,0,179,181,3,4,2,0,180,174,1,0,0,0,180,179,1,0,0,0,181,23,1,0,
		0,0,182,183,7,0,0,0,183,184,3,32,16,0,184,185,5,46,0,0,185,186,3,40,20,
		0,186,25,1,0,0,0,187,188,3,48,24,0,188,189,5,46,0,0,189,190,3,40,20,0,
		190,27,1,0,0,0,191,192,3,48,24,0,192,193,5,39,0,0,193,194,3,40,20,0,194,
		29,1,0,0,0,195,196,3,48,24,0,196,197,7,1,0,0,197,31,1,0,0,0,198,201,3,
		48,24,0,199,200,5,7,0,0,200,202,3,48,24,0,201,199,1,0,0,0,201,202,1,0,
		0,0,202,33,1,0,0,0,203,204,3,48,24,0,204,205,5,6,0,0,205,206,3,48,24,0,
		206,207,5,8,0,0,207,208,3,40,20,0,208,35,1,0,0,0,209,210,3,48,24,0,210,
		211,5,18,0,0,211,212,3,40,20,0,212,213,5,20,0,0,213,214,3,40,20,0,214,
		215,5,19,0,0,215,216,3,40,20,0,216,37,1,0,0,0,217,218,3,48,24,0,218,219,
		5,21,0,0,219,220,3,40,20,0,220,221,5,22,0,0,221,222,3,40,20,0,222,223,
		5,23,0,0,223,224,3,40,20,0,224,39,1,0,0,0,225,226,6,20,-1,0,226,227,5,
		2,0,0,227,228,3,40,20,0,228,229,5,3,0,0,229,244,1,0,0,0,230,231,5,9,0,
		0,231,244,3,40,20,19,232,233,5,41,0,0,233,244,3,40,20,18,234,244,3,48,
		24,0,235,244,5,32,0,0,236,244,5,33,0,0,237,244,5,34,0,0,238,244,3,42,21,
		0,239,244,3,46,23,0,240,244,5,11,0,0,241,244,3,56,28,0,242,244,3,20,10,
		0,243,225,1,0,0,0,243,230,1,0,0,0,243,232,1,0,0,0,243,234,1,0,0,0,243,
		235,1,0,0,0,243,236,1,0,0,0,243,237,1,0,0,0,243,238,1,0,0,0,243,239,1,
		0,0,0,243,240,1,0,0,0,243,241,1,0,0,0,243,242,1,0,0,0,244,274,1,0,0,0,
		245,246,10,17,0,0,246,247,5,44,0,0,247,273,3,40,20,18,248,249,10,16,0,
		0,249,250,5,36,0,0,250,273,3,40,20,17,251,252,10,15,0,0,252,253,5,37,0,
		0,253,273,3,40,20,16,254,255,10,14,0,0,255,256,5,61,0,0,256,273,3,40,20,
		15,257,258,10,13,0,0,258,259,5,62,0,0,259,273,3,40,20,14,260,261,10,12,
		0,0,261,262,5,38,0,0,262,273,3,40,20,13,263,264,10,3,0,0,264,265,5,12,
		0,0,265,266,3,40,20,0,266,267,5,7,0,0,267,268,3,40,20,4,268,273,1,0,0,
		0,269,270,10,5,0,0,270,271,5,10,0,0,271,273,3,48,24,0,272,245,1,0,0,0,
		272,248,1,0,0,0,272,251,1,0,0,0,272,254,1,0,0,0,272,257,1,0,0,0,272,260,
		1,0,0,0,272,263,1,0,0,0,272,269,1,0,0,0,273,276,1,0,0,0,274,272,1,0,0,
		0,274,275,1,0,0,0,275,41,1,0,0,0,276,274,1,0,0,0,277,278,5,4,0,0,278,283,
		3,44,22,0,279,280,5,6,0,0,280,282,3,44,22,0,281,279,1,0,0,0,282,285,1,
		0,0,0,283,281,1,0,0,0,283,284,1,0,0,0,284,286,1,0,0,0,285,283,1,0,0,0,
		286,287,5,5,0,0,287,43,1,0,0,0,288,289,3,40,20,0,289,290,5,46,0,0,290,
		291,3,40,20,0,291,45,1,0,0,0,292,301,5,13,0,0,293,298,3,40,20,0,294,295,
		5,6,0,0,295,297,3,40,20,0,296,294,1,0,0,0,297,300,1,0,0,0,298,296,1,0,
		0,0,298,299,1,0,0,0,299,302,1,0,0,0,300,298,1,0,0,0,301,293,1,0,0,0,301,
		302,1,0,0,0,302,303,1,0,0,0,303,304,5,14,0,0,304,47,1,0,0,0,305,309,5,
		35,0,0,306,308,3,50,25,0,307,306,1,0,0,0,308,311,1,0,0,0,309,307,1,0,0,
		0,309,310,1,0,0,0,310,49,1,0,0,0,311,309,1,0,0,0,312,315,3,52,26,0,313,
		315,3,54,27,0,314,312,1,0,0,0,314,313,1,0,0,0,315,51,1,0,0,0,316,317,5,
		10,0,0,317,318,5,35,0,0,318,53,1,0,0,0,319,320,5,13,0,0,320,321,3,40,20,
		0,321,322,5,14,0,0,322,55,1,0,0,0,323,324,5,28,0,0,324,333,5,2,0,0,325,
		330,3,32,16,0,326,327,5,6,0,0,327,329,3,32,16,0,328,326,1,0,0,0,329,332,
		1,0,0,0,330,328,1,0,0,0,330,331,1,0,0,0,331,334,1,0,0,0,332,330,1,0,0,
		0,333,325,1,0,0,0,333,334,1,0,0,0,334,335,1,0,0,0,335,336,5,3,0,0,336,
		338,5,4,0,0,337,339,3,2,1,0,338,337,1,0,0,0,338,339,1,0,0,0,339,340,1,
		0,0,0,340,341,5,5,0,0,341,57,1,0,0,0,32,64,69,84,92,96,99,104,108,116,
		120,127,132,136,140,153,156,168,171,176,180,201,243,272,274,283,298,301,
		309,314,330,333,338
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
