//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VoxScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVoxScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.actionSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActionSet([NotNull] VoxScriptParser.ActionSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.actionSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActionSet([NotNull] VoxScriptParser.ActionSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] VoxScriptParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] VoxScriptParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_set([NotNull] VoxScriptParser.Var_setContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_set([NotNull] VoxScriptParser.Var_setContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_inst([NotNull] VoxScriptParser.Var_instContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_inst([NotNull] VoxScriptParser.Var_instContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_object([NotNull] VoxScriptParser.For_objectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_object([NotNull] VoxScriptParser.For_objectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_repeat([NotNull] VoxScriptParser.For_repeatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_repeat([NotNull] VoxScriptParser.For_repeatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFor_range([NotNull] VoxScriptParser.For_rangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFor_range([NotNull] VoxScriptParser.For_rangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] VoxScriptParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] VoxScriptParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.objItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjItem([NotNull] VoxScriptParser.ObjItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.objItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjItem([NotNull] VoxScriptParser.ObjItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArray([NotNull] VoxScriptParser.ArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArray([NotNull] VoxScriptParser.ArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIden_seg([NotNull] VoxScriptParser.Iden_segContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIden_seg([NotNull] VoxScriptParser.Iden_segContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIden_seg_text([NotNull] VoxScriptParser.Iden_seg_textContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIden_seg_text([NotNull] VoxScriptParser.Iden_seg_textContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIden_seg_expr([NotNull] VoxScriptParser.Iden_seg_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIden_seg_expr([NotNull] VoxScriptParser.Iden_seg_exprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_expr([NotNull] VoxScriptParser.Func_exprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_expr([NotNull] VoxScriptParser.Func_exprContext context);
}
