//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="VoxScriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IVoxScriptVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] VoxScriptParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.actionSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionSet([NotNull] VoxScriptParser.ActionSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] VoxScriptParser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_if([NotNull] VoxScriptParser.Cont_ifContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_else([NotNull] VoxScriptParser.Cont_elseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_while([NotNull] VoxScriptParser.Cont_whileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_for([NotNull] VoxScriptParser.Cont_forContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_return([NotNull] VoxScriptParser.Cont_returnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_break([NotNull] VoxScriptParser.Cont_breakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_call([NotNull] VoxScriptParser.Func_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_define([NotNull] VoxScriptParser.Func_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_define([NotNull] VoxScriptParser.Var_defineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_set"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_set([NotNull] VoxScriptParser.Var_setContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_arith"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_arith([NotNull] VoxScriptParser.Var_arithContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_incre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_incre([NotNull] VoxScriptParser.Var_increContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVar_inst([NotNull] VoxScriptParser.Var_instContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.for_object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_object([NotNull] VoxScriptParser.For_objectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.for_repeat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_repeat([NotNull] VoxScriptParser.For_repeatContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.for_range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_range([NotNull] VoxScriptParser.For_rangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] VoxScriptParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] VoxScriptParser.ObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.objItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjItem([NotNull] VoxScriptParser.ObjItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] VoxScriptParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] VoxScriptParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.iden_seg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIden_seg([NotNull] VoxScriptParser.Iden_segContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.iden_seg_text"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIden_seg_text([NotNull] VoxScriptParser.Iden_seg_textContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.iden_seg_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIden_seg_expr([NotNull] VoxScriptParser.Iden_seg_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="VoxScriptParser.func_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunc_expr([NotNull] VoxScriptParser.Func_exprContext context);
}
