//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VoxScript.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IVoxScriptListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class VoxScriptBaseListener : IVoxScriptListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] VoxScriptParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] VoxScriptParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.actionSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActionSet([NotNull] VoxScriptParser.ActionSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.actionSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActionSet([NotNull] VoxScriptParser.ActionSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] VoxScriptParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] VoxScriptParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_if([NotNull] VoxScriptParser.Cont_ifContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_if"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_if([NotNull] VoxScriptParser.Cont_ifContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_else([NotNull] VoxScriptParser.Cont_elseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_else"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_else([NotNull] VoxScriptParser.Cont_elseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_while([NotNull] VoxScriptParser.Cont_whileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_while"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_while([NotNull] VoxScriptParser.Cont_whileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_for([NotNull] VoxScriptParser.Cont_forContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_for"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_for([NotNull] VoxScriptParser.Cont_forContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_return([NotNull] VoxScriptParser.Cont_returnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_return"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_return([NotNull] VoxScriptParser.Cont_returnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_break([NotNull] VoxScriptParser.Cont_breakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_break"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_break([NotNull] VoxScriptParser.Cont_breakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCont_continue([NotNull] VoxScriptParser.Cont_continueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.cont_continue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCont_continue([NotNull] VoxScriptParser.Cont_continueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call([NotNull] VoxScriptParser.Func_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call([NotNull] VoxScriptParser.Func_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_define([NotNull] VoxScriptParser.Func_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_define([NotNull] VoxScriptParser.Func_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_define([NotNull] VoxScriptParser.Var_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_define([NotNull] VoxScriptParser.Var_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_set([NotNull] VoxScriptParser.Var_setContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_set"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_set([NotNull] VoxScriptParser.Var_setContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_arith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_arith([NotNull] VoxScriptParser.Var_arithContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_arith"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_arith([NotNull] VoxScriptParser.Var_arithContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_incre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_incre([NotNull] VoxScriptParser.Var_increContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_incre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_incre([NotNull] VoxScriptParser.Var_increContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_inst([NotNull] VoxScriptParser.Var_instContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.var_inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_inst([NotNull] VoxScriptParser.Var_instContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_define([NotNull] VoxScriptParser.Type_defineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_define"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_define([NotNull] VoxScriptParser.Type_defineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_inherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_inherit([NotNull] VoxScriptParser.Type_inheritContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_inherit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_inherit([NotNull] VoxScriptParser.Type_inheritContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_member([NotNull] VoxScriptParser.Type_memberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_member"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_member([NotNull] VoxScriptParser.Type_memberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_field([NotNull] VoxScriptParser.Type_fieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_field"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_field([NotNull] VoxScriptParser.Type_fieldContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_function([NotNull] VoxScriptParser.Type_functionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_function"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_function([NotNull] VoxScriptParser.Type_functionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.type_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_reference([NotNull] VoxScriptParser.Type_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.type_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_reference([NotNull] VoxScriptParser.Type_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_object([NotNull] VoxScriptParser.For_objectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_object([NotNull] VoxScriptParser.For_objectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_repeat([NotNull] VoxScriptParser.For_repeatContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_repeat"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_repeat([NotNull] VoxScriptParser.For_repeatContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.for_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFor_range([NotNull] VoxScriptParser.For_rangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.for_range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFor_range([NotNull] VoxScriptParser.For_rangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] VoxScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] VoxScriptParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] VoxScriptParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] VoxScriptParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.objItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjItem([NotNull] VoxScriptParser.ObjItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.objItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjItem([NotNull] VoxScriptParser.ObjItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArray([NotNull] VoxScriptParser.ArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArray([NotNull] VoxScriptParser.ArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] VoxScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] VoxScriptParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIden_seg([NotNull] VoxScriptParser.Iden_segContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIden_seg([NotNull] VoxScriptParser.Iden_segContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIden_seg_text([NotNull] VoxScriptParser.Iden_seg_textContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg_text"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIden_seg_text([NotNull] VoxScriptParser.Iden_seg_textContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.iden_seg_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIden_seg_expr([NotNull] VoxScriptParser.Iden_seg_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.iden_seg_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIden_seg_expr([NotNull] VoxScriptParser.Iden_seg_exprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="VoxScriptParser.func_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_expr([NotNull] VoxScriptParser.Func_exprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="VoxScriptParser.func_expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_expr([NotNull] VoxScriptParser.Func_exprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
